/*
 * generated by Xtext
 */
package org.lunifera.examples.ecview.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MasterDetailDSLRuntimeModule extends org.lunifera.examples.ecview.dsl.AbstractMasterDetailDSLRuntimeModule {

}
