/*
 * generated by Xtext
 */
package org.lunifera.examples.ecview.dsl.ui.contentassist

import org.lunifera.examples.ecview.dsl.ui.contentassist.AbstractMasterDetailDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MasterDetailDSLProposalProvider extends AbstractMasterDetailDSLProposalProvider {
}
