/*
 * generated by Xtext
 */
package org.lunifera.examples.ecview.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MasterDetailDSLUiModule extends org.lunifera.examples.ecview.dsl.ui.AbstractMasterDetailDSLUiModule {
	public MasterDetailDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
